[package]
name = "bigdecimal"
version = "0.0.7"
authors = ["Andrew Kubera"]
description = "Arbitrary percision decimal numbers"
documentation = "https://docs.rs/bigdecimal"
homepage = "https://github.com/akubera/bigdecimal-rs"
repository = "https://github.com/akubera/bigdecimal-rs"
keywords = ["mathematics", "numerics", "decimal", "arbitrary precision", "floating-point"]
license = "MIT/Apache-2.0"

[dependencies]
num = { version = "0.1.37", default-features=false, features=["bigint"] }
num-traits = "0.1.37"

[dev-dependencies.rand]
version = "0.3"

